#!/bin/sh

crash=crash
WDIR=${WDIR:-"$HOME/work"}
debug=$(ls ./vmlinux.debug 2>/dev/null)

if [ -f ./crash ]; then
	crash=./crash
else
	if [ -d ./lustre_kos ]; then
		crash=crash_sles
	fi
fi

export PYKDUMPPATH=$WDIR/pycrashext:$WDIR/lustredbg:$WDIR/pykdump
export CRASH_EXTENSIONS=$WDIR/crash_ext

[ -z $TMUX ] || tmux rename-window $(basename $(pwd))

$crash -x -i ./load_modules ./vmlinux $debug $*
