#!/bin/sh

core=$1
crash=crash
WDIR=${WDIR:-"$HOME/work"}

if [ -f ./crash ]; then
	crash=./crash
else
	if [ -d ./lustre_kos ]; then
		crash=crash-7.0.1-29bit
	fi
fi

if [ -d ./lustre_kos ]; then
	mod_cmd="mod -S ./lustre_kos \n"
else
	while IFS= read -r line ; do
		mod_cmd="$mod_cmd $line \n"
	done < "load_modules"
fi

printf "$mod_cmd $2 \n q" | CRASH_EXTENSIONS=$WDIR/crash_ext $crash -s -x ./vmlinux $core
