#!/bin/sh

crash=crash
WDIR=${WDIR:-"$HOME/work"}

if [ -f ./crash ]; then
	crash=./crash
else
	if [ -d ./lustre_kos ]; then
		crash=crash-7.2.5_sles
	fi
fi

export PYKDUMPPATH=$WDIR/pycrashext:$WDIR/lustredbg:$WDIR/pykdump
export CRASH_EXTENSIONS=$WDIR/crash_ext

$crash -x -i ./load_modules ./vmlinux $1
