#!/bin/sh

core=$1
crash=crash

if [ -f ./crash ]; then
	crash=./crash
else
	if [ -d ./lustre_kos ]; then
		crash=crash-7.2.5_sles
	fi
fi

if [ -d ./lustre_kos ]; then
	mod_cmd="mod -S ./lustre_kos \n"
else
	while IFS= read -r line ; do
		mod_cmd="$mod_cmd $line \n"
	done < "load_modules"
fi

printf "$mod_cmd $2 \n q" | $crash -s ./vmlinux $core
