#!/bin/sh

[ -f load_modules ] || exit

log_extr $1 &
vmcore_stack $1 &
dump_dmesg $1
if grep "SysRq : Trigger a crash" dmesg_$1
then
	vmcore_sysrq $1 &
	wait
else
	vmcore_fp $1 &
	wait

	core=$(basename $1)
	pid=$(grep PID analysis_$core | cut -d' ' -f 2 |uniq)
	grep ":"$pid":" log.dk_$core | tail >> analysis_$core
fi

